Ticket center Permission, Pagination, PageList, lastUpdateDate
kixiQu/ticketdesk pull request #29
Opened 2018-04-28 20:36 UTC by JoschaO

Added Permission based for ticketlists
Pagination as seperate input, that doesn't need max page from backend
Switch from Index to PageList for Daniel
Fixed lastUpdateDate 
Made a little more pretty

2018-04-28 20:47 UTC, kixiQu requested changes
There are some things here that I would probably do differently--the magic strings defining roles are an app setting on the back end, so having them built into the model files (rather than in app-settings or something) seems sketchy to me--but then again, we have to build that logic in, too. Maybe there are no good answers.

Anyway, delete the perm and I think it's good

2018-04-28 20:47 UTC, kixiQu commented on TicketDesk/ngWebClient-StandAlone/src/app/ticket-center/ticket-center.component.ts
> +    console.warn('Gonna go get a perm. For the curls.');
This should probably not be here.

2018-04-28 20:47 UTC, ColinStClaire submitted a review, later dismissed
Looks good

2018-04-28 20:49 UTC, ColinStClaire submitted a review, later dismissed
Looks good

2018-04-29 18:03 UTC, kixiQu approved these changes
yeeeeeee

2018-04-29 18:03 UTC, merged